### ISSUE TITLE
Submodules can't be resolved

### ISSUE THREAD

**Issue by jsamr** [expo/snack#141]
### Summary

Submodules are not resolved by the Snack bundler. For example `'@jsamr/counter-style/presets/thai'` will raise the following error:

![image](https://user-images.githubusercontent.com/3646758/118736226-71a07880-b818-11eb-8376-ad5a5fc81ef3.png)

while it will work with metro or Webpack bundlers.

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

Production (SDK 41)

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.io/@jsamr/submodules-expo-bug

Also note that dependencies that in turn depend on the same submodules **don't raise the above error**.

**Comment by IjzerenHein** [comment]
That is correct. This is because Snack converts packages into bundles (which can be loaded by the runtime) which do not expose the path that you are trying to import. As a solution, Snack allows you to add the import as a dependency, which will cause a bundle to be created for that import. I've verified that this works with your example. Just click on "Add dependency" to add it to your list of dependencies.

**Comment by jsamr** [comment]
@IjzerenHein Copy that! Duh, was one click away. Thanks!
