### ISSUE TITLE
Can not install @react-native-community/datetimepicker as a dependency in SDK 45

### ISSUE THREAD

**Issue by riebel** [expo/snack#305]
### Summary

If I try to add '@react-native-community/datetimepicker' via import i get the following error:

`Failed to resolve dependency '@react-native-community/datetimepicker@6.1.2' (Invalid module ./picker - Module not found: Error: Can't resolve './picker' in '/tmp/snackager/snackager/buildStatus/1/@react-native-community~datetimepicker@6.1.2-ios,android,web/package/src')`

`@react-native-community/datetimepicker@6.1.2` seems to be the correct expo SDK 45 version. 
SDK 44 uses `@react-native-community/datetimepicker@4.0.0` and works just fine.

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

45

### Reproducible demo or steps to reproduce from a blank project

- create a new Snack,
- switch to SDK 45
- insert `import DateTimePicker from '@react-native-community/datetimepicker';`
- click 'Add dependency'

**Comment by byCedric** [comment]
Hi! It seems that this datetimepicker ships with Flow code instead of JavaScript. You can see the exact error here: https://github.com/expo/snack/runs/7412953809?check_suite_focus=true#step:6:161. This is not something we can fix, the library author should ship with non-flow code to allow us to bundle the code and use it in Snack.

Please open a new issue at https://github.com/react-native-datetimepicker/datetimepicker mentioning this.

**Comment by byCedric** [comment]
Closing this issue in favor of https://github.com/expo/snack/issues/257
