### ISSUE TITLE
The App Doesn't Work While Running It on your own Phone.

### ISSUE THREAD

**Issue by haneenmahd** [expo/snack#44]
### Summary of Issue 
App Just Turn off with a flashy screen after loading the splashscreen

### Expected Behavior vs Actual Behavior
It Just Turn off With a Flashy Screen

**Comment by IjzerenHein** [comment]
Hi. Please provide a way for us to reproduce this issue. A link to the Snack that doesn't work would be ideal.

**Comment by haneenmahd** [comment]
This is just my snack to create a  User Interface of a Payment App
[link For my snack](https://snack.expo.io/@haneenmahdin/payment-app)

**Comment by IjzerenHein** [comment]
The problem is with `<LinearGradient>`. You cannot provide `Animated.Value`s to the LinearGradient component directly. You'll either need to wrap it with [createAnimatedComponent](https://reactnative.dev/docs/animated#createanimatedcomponent), but I'm not even sure that that scenario is supported by LinearGradient.

**Comment by haneenmahd** [comment]
Thanks for the help
