### ISSUE TITLE
Stylesheet object not validating style property names

### ISSUE THREAD

**Issue by amandeepmittal** [expo/snack#52]
In an Expo snack, I found this behaviour of not throwing an error when a style property name is misspelled inside the `StyleSheet.create()` object.

For example:

```js
const styles = StyleSheet.create({
    backgroundClor: 'tomato',
})
```

As per the expected behaviour in React Native and Expo apps, an error is thrown in this scenario. I am not sure if this behaviour is known or not (in terms of Expo Snack).

Here is an example in the snack: [https://snack.expo.io/@amanhimself/cad717](https://snack.expo.io/@amanhimself/cad717).

**Comment by IjzerenHein** [comment]
This happens because Snack uses the production version of react-native, which does not perform style validation. On `react-native` you would get an error like this in development:

![image](https://user-images.githubusercontent.com/6184593/133593745-0ef0ec0e-cb62-4c2e-8a4a-7e42ca35d962.png)

However, you also wouldn't see an error in the editor, just a runtime error when running the code while in development.

I'm not sure how to deal with this though. We'd probably have to introduce a dev vs production mode to make this happen..

**Comment by amandeepmittal** [comment]
Thanks for getting back on this @IjzerenHein and explaining about the Snack's core. I didn't know that. Also, I don't think if this is significant enough to address.

**Comment by IjzerenHein** [comment]
> Thanks for getting back on this @IjzerenHein and explaining about the Snack's core. I didn't know that. Also, I don't think if this is significant enough to address.

Yeah I agree. It would be nice, but it's not that important. 👍
