### ISSUE TITLE
Please don't suppress react native warnings

### ISSUE THREAD

**Issue by EskelCz** [expo/snack#55]
Hi. I love snack but this irks me. I was trying to showcase a RN warning to a react developer who doesn't use RN. He asked me for a minimal implementation.

So I've made a Snack... and found out the warning is not shown in your console.

I accept that you removed YellowBox from your fork, but please show the same warnings in your console. Snack is the only RN playground at the moment, so I think it's pretty important.
Thanks.

**Comment by IjzerenHein** [comment]
Hi! It's been a while since this issue was reported. We've rolled out many features and bug-fixes since then. I believe this particular issue has been resolved and the Snack Runtime no longer suppresses the mentioned warnings. If it still does, feel free to reopen this issue with additional reproduction information.
